In [1]:
from keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()


11490434/11490434 [==============================] - 0s 0us/step


In [2]:
train_images.shape


(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape


(10000, 28, 28)

In [6]:
len(test_images)


10000

In [7]:
test_labels


array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))


In [9]:
network.compile(optimizer='rmsprop',
        loss='categorical_crossentropy',
        metrics=['accuracy'])


In [10]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255


In [11]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)


In [12]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)


Epoch 1/5
469/469 [==============================] - 6s 10ms/step - loss: 0.2631 - accuracy: 0.9246
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1064 - accuracy: 0.9691
Epoch 3/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0695 - accuracy: 0.9794
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0515 - accuracy: 0.9843
Epoch 5/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0390 - accuracy: 0.9885


In [14]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_accuracy:', test_acc)


313/313 [==============================] - 2s 5ms/step - loss: 0.0596 - accuracy: 0.9817
test_accuracy: 0.9817000031471252


In [15]:
import numpy as np
x = np.array(12)
x


array(12)

In [16]:
scalar_tensor = np.array(5)
print("Scalar Tensor:\n", scalar_tensor)


Scalar Tensor:
 5


In [17]:
vector_tensor = np.array([1, 2, 3])
print("\nVector Tensor:\n", vector_tensor)



Vector Tensor:
 [1 2 3]


In [18]:
matrix_tensor = np.array([[1, 2], [3, 4]])
print("\nMatrix Tensor:\n", matrix_tensor)



Matrix Tensor:
 [[1 2]
 [3 4]]


In [19]:
tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Tensor:\n", tensor_3d)
print(tensor_3d.shape)



3D Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [20]:
random_tensor = np.random.normal(size=(3, 3))
print("\nRandom Tensor:\n", random_tensor)



Random Tensor:
 [[ 0.0208198  -0.64750911 -1.3605315 ]
 [-0.14076705  0.13881233  0.37278787]
 [ 0.25217761 -0.69063304  1.86387368]]


In [21]:
import numpy as np

# Create a 3D tensor
tensor_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                      [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

# Reshape the tensor to a 2D tensor
tensor_2d = tensor_3d.reshape((2, 12))

# Print the shapes of the tensors
print("Original Tensor Shape:", tensor_3d.shape)
print("Reshaped Tensor Shape:", tensor_2d.shape)


Original Tensor Shape: (2, 3, 4)
Reshaped Tensor Shape: (2, 12)


In [22]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dot(a, b)

print(result)


[[19 22]
 [43 50]]
