In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [3]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [4]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [5]:
a = np.array([10, 11, 12, 13, 14, 15])
b = np.array([20, 21, 22, 23, 24, 25])

c = np.add(a, b)

print(c)


[30 32 34 36 38 40]


In [7]:
a = np.array([10, 11, 12, 13, 14, 15])
b = np.array([20, 21, 22, 23, 24, 25])

c = np.subtract(a , b)

print(c)

[-10 -10 -10 -10 -10 -10]


In [8]:
a = np.array([10, 11, 12, 13, 14, 15])
b = np.array([20, 21, 22, 23, 24, 25])

c = np.multiply(a , b)

print(c)

[200 231 264 299 336 375]


In [9]:
a = np.array([10, 11, 12, 13, 14, 15])
b = np.array([20, 21, 22, 23, 24, 25])

c = np.divide(a , b)

print(c)

[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
