In [2]:
import numpy as np  
a = np.array([[200,200],[23,12]])  
b = np.array([[10,5],[400,21]])  
dot = np.dot(a,b)  
print(dot)  


[[82000  5200]
 [ 5030   367]]


In [3]:
print(np.vdot(a,b))

12452


In [4]:
print(np.inner(a,b))

[[ 3000 84200]
 [  290  9452]]


In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
b = np.array([[23,23,12],[2,1,2],[7,8,9]])  
mul = np.matmul(a,b)  
print(mul)  


[[ 48  49  43]
 [144 145 112]
 [240 241 181]]


In [7]:
a = np.array([[1,2],[3,4]])  
print(np.linalg.det(a))

-2.0000000000000004


In [8]:
a = np.array([[1,2],[3,4]])  
b = np.array([[1,2],[3,4]])  
print(np.linalg.solve(a, b))  


[[1. 0.]
 [0. 1.]]


In [9]:
a = np.array([[1,2],[3,4]])  
print("Original array:\n",a)  
b = np.linalg.inv(a)  
print("Inverse:\n",b)  


Original array:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
